"""
Synthetic generator for Chilean e-commerce / card-present payment transactions
(Transbank/Redcompra-style), with an injected, extreme-imbalance fraud pattern.

The fraud pattern is not a random label flip: it is generated by a distinct
process (account-takeover / card-testing bursts) so that the engineered
features in ``src/features`` (transaction velocity, geographic jump speed,
deviation from the customer's habitual amount) carry real signal.
"""
from __future__ import annotations

import numpy as np
import pandas as pd

# Approx (lat, lon) centroids for major Chilean cities, used as customer "home" bases.
CHILEAN_CITIES = {
    "Santiago": (-33.4489, -70.6693),
    "Valparaiso": (-33.0472, -71.6127),
    "Concepcion": (-36.8201, -73.0444),
    "La Serena": (-29.9027, -71.2519),
    "Antofagasta": (-23.6509, -70.3975),
    "Temuco": (-38.7359, -72.5904),
    "Rancagua": (-34.1708, -70.7444),
    "Iquique": (-20.2141, -70.1522),
    "Puerto Montt": (-41.4693, -72.9424),
    "Chillan": (-36.6066, -72.1034),
}

MERCHANT_CATEGORIES = [
    "supermercado", "restaurante", "combustible", "farmacia", "retail",
    "electronica", "servicios_basicos", "entretenimiento", "vestuario",
    "e-commerce_general",
]

# Typical CLP spend by category (lognormal mean, sigma) -> realistic long right tail.
CATEGORY_AMOUNT_PARAMS = {
    "supermercado": (10.6, 0.5),
    "restaurante": (9.8, 0.55),
    "combustible": (10.2, 0.35),
    "farmacia": (9.5, 0.6),
    "retail": (10.9, 0.7),
    "electronica": (12.2, 0.9),
    "servicios_basicos": (10.3, 0.3),
    "entretenimiento": (9.9, 0.5),
    "vestuario": (10.5, 0.6),
    "e-commerce_general": (10.7, 0.8),
}

EARTH_RADIUS_KM = 6371.0


def _haversine_km(lat1, lon1, lat2, lon2) -> np.ndarray:
    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = np.sin(dlat / 2.0) ** 2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon / 2.0) ** 2
    return 2 * EARTH_RADIUS_KM * np.arcsin(np.sqrt(np.clip(a, 0.0, 1.0)))


def _build_customer_profiles(n_customers: int, rng: np.random.Generator) -> pd.DataFrame:
    city_names = list(CHILEAN_CITIES.keys())
    # Santiago is disproportionately represented, matching real card-network volume.
    city_weights = np.array([0.42, 0.10, 0.09, 0.06, 0.07, 0.07, 0.05, 0.05, 0.05, 0.04])
    home_city = rng.choice(city_names, size=n_customers, p=city_weights)

    home_lat = np.empty(n_customers)
    home_lon = np.empty(n_customers)
    for i, city in enumerate(home_city):
        base_lat, base_lon = CHILEAN_CITIES[city]
        # Jitter within ~15km of the city centroid to spread customers around town.
        home_lat[i] = base_lat + rng.normal(0, 0.07)
        home_lon[i] = base_lon + rng.normal(0, 0.07)

    # Each customer has a habitual spend level (log-normal) and preferred category mix.
    avg_amount = rng.lognormal(mean=10.3, sigma=0.55, size=n_customers)
    amount_std = avg_amount * rng.uniform(0.15, 0.45, size=n_customers)

    return pd.DataFrame({
        "customer_id": np.arange(n_customers),
        "home_city": home_city,
        "home_lat": home_lat,
        "home_lon": home_lon,
        "avg_amount_clp": avg_amount,
        "amount_std_clp": amount_std,
    })


def _simulate_legit_transactions(
    customers: pd.DataFrame,
    n_transactions: int,
    start_ts: pd.Timestamp,
    end_ts: pd.Timestamp,
    rng: np.random.Generator,
) -> pd.DataFrame:
    n_customers = len(customers)
    # Not all customers transact equally often -> Poisson-ish skew via lognormal weights.
    activity_weight = rng.lognormal(mean=0, sigma=0.8, size=n_customers)
    activity_weight /= activity_weight.sum()
    cust_idx = rng.choice(n_customers, size=n_transactions, p=activity_weight)

    span_seconds = (end_ts - start_ts).total_seconds()
    # Transaction volume follows a day/night curve: peaks ~12-14h and ~19-21h local time.
    raw_seconds = rng.uniform(0, span_seconds, size=n_transactions)
    hours = (raw_seconds / 3600.0) % 24.0
    hour_weight = (
        0.35
        + 0.9 * np.exp(-((hours - 13.0) ** 2) / (2 * 3.0 ** 2))
        + 1.1 * np.exp(-((hours - 20.0) ** 2) / (2 * 2.5 ** 2))
    )
    accept = rng.uniform(0, hour_weight.max(), size=n_transactions) < hour_weight
    # Resample rejected timestamps a few times to keep the target count roughly intact.
    for _ in range(4):
        n_reject = int((~accept).sum())
        if n_reject == 0:
            break
        resample = rng.uniform(0, span_seconds, size=n_reject)
        rhours = (resample / 3600.0) % 24.0
        rweight = (
            0.35
            + 0.9 * np.exp(-((rhours - 13.0) ** 2) / (2 * 3.0 ** 2))
            + 1.1 * np.exp(-((rhours - 20.0) ** 2) / (2 * 2.5 ** 2))
        )
        raccept = rng.uniform(0, hour_weight.max(), size=n_reject) < rweight
        idx = np.where(~accept)[0]
        raw_seconds[idx[raccept]] = resample[raccept]
        accept[idx[raccept]] = True

    timestamps = start_ts + pd.to_timedelta(raw_seconds, unit="s")

    categories = rng.choice(MERCHANT_CATEGORIES, size=n_transactions)

    cust = customers.iloc[cust_idx].reset_index(drop=True)
    amounts = np.empty(n_transactions)
    for cat in MERCHANT_CATEGORIES:
        mask = categories == cat
        n_cat = mask.sum()
        if n_cat == 0:
            continue
        mu, sigma = CATEGORY_AMOUNT_PARAMS[cat]
        # Blend the category baseline with the customer's own habitual level.
        cat_amount = rng.lognormal(mean=mu, sigma=sigma, size=n_cat)
        personal_scale = cust["avg_amount_clp"].to_numpy()[mask] / np.exp(10.3)
        amounts[mask] = cat_amount * np.clip(personal_scale, 0.4, 3.0)

    # Legit transactions happen near the customer's home base, small local jitter.
    lat = cust["home_lat"].to_numpy() + rng.normal(0, 0.04, size=n_transactions)
    lon = cust["home_lon"].to_numpy() + rng.normal(0, 0.04, size=n_transactions)

    df = pd.DataFrame({
        "customer_id": cust["customer_id"].to_numpy(),
        "timestamp": timestamps,
        "amount_clp": np.round(amounts, 0),
        "merchant_category": categories,
        "latitude": lat,
        "longitude": lon,
        "is_fraud": 0,
    })
    return df


def _simulate_fraud_transactions(
    customers: pd.DataFrame,
    n_fraud_events: int,
    start_ts: pd.Timestamp,
    end_ts: pd.Timestamp,
    rng: np.random.Generator,
) -> pd.DataFrame:
    """Each 'fraud event' is a short burst of 1-6 rapid transactions (card testing /
    account takeover) at a location far from the victim's home base."""
    span_seconds = (end_ts - start_ts).total_seconds()
    city_names = list(CHILEAN_CITIES.keys())

    rows = []
    victim_idx = rng.choice(len(customers), size=n_fraud_events, replace=False)
    for k, ci in enumerate(victim_idx):
        cust = customers.iloc[ci]
        event_start = start_ts + pd.to_timedelta(rng.uniform(0, span_seconds), unit="s")

        # Attacker location: a different city than the victim's home, far away.
        other_cities = [c for c in city_names if c != cust["home_city"]]
        fraud_city = rng.choice(other_cities)
        base_lat, base_lon = CHILEAN_CITIES[fraud_city]
        fraud_lat = base_lat + rng.normal(0, 0.05)
        fraud_lon = base_lon + rng.normal(0, 0.05)

        burst_size = rng.integers(1, 7)
        # Rapid-fire: seconds to a few minutes apart (velocity attack signature).
        gaps = rng.uniform(15, 240, size=burst_size)
        gaps[0] = 0
        offsets = np.cumsum(gaps)

        # Amounts: either abnormally small (card testing) or abnormally large
        # (cash-out), both far from the victim's habitual amount.
        if rng.random() < 0.5:
            amt = rng.uniform(500, 3000, size=burst_size)
        else:
            amt = cust["avg_amount_clp"] * rng.uniform(6, 25, size=burst_size)

        for j in range(burst_size):
            rows.append({
                "customer_id": cust["customer_id"],
                "timestamp": event_start + pd.to_timedelta(offsets[j], unit="s"),
                "amount_clp": round(float(amt[j]), 0),
                "merchant_category": rng.choice(MERCHANT_CATEGORIES),
                "latitude": fraud_lat + rng.normal(0, 0.01),
                "longitude": fraud_lon + rng.normal(0, 0.01),
                "is_fraud": 1,
            })

    return pd.DataFrame(rows)


def time_based_split(
    df: pd.DataFrame, train_frac: float = 0.70, val_frac: float = 0.15
) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """Splits chronologically (by timestamp) rather than randomly, so the
    model is always trained on the past and evaluated on the future -- a
    random split would leak a customer's later transactions into training
    and understate real-world generalization error.
    """
    df = df.sort_values("timestamp").reset_index(drop=True)
    n = len(df)
    train_end = int(n * train_frac)
    val_end = int(n * (train_frac + val_frac))
    return df.iloc[:train_end].copy(), df.iloc[train_end:val_end].copy(), df.iloc[val_end:].copy()


def generate_dataset(
    n_transactions: int = 100_000,
    fraud_rate: float = 0.007,
    n_customers: int = 6_000,
    start_date: str = "2026-02-01",
    n_days: int = 60,
    seed: int = 42,
) -> pd.DataFrame:
    """Generate a synthetic Chilean payments dataset with < 1% fraud.

    Returns a DataFrame sorted by (customer_id, timestamp), which downstream
    feature engineering (velocity, geo-distance) relies on.
    """
    rng = np.random.default_rng(seed)
    start_ts = pd.Timestamp(start_date)
    end_ts = start_ts + pd.Timedelta(days=n_days)

    customers = _build_customer_profiles(n_customers, rng)

    n_fraud_target = max(1, int(n_transactions * fraud_rate))
    # Each fraud "event" yields ~3.5 rows on average -> back out event count.
    n_fraud_events = max(1, int(n_fraud_target / 3.5))

    fraud_df = _simulate_fraud_transactions(customers, n_fraud_events, start_ts, end_ts, rng)
    n_legit = n_transactions - len(fraud_df)
    legit_df = _simulate_legit_transactions(customers, n_legit, start_ts, end_ts, rng)

    df = pd.concat([legit_df, fraud_df], ignore_index=True)
    df = df.sort_values(["customer_id", "timestamp"]).reset_index(drop=True)
    df["transaction_id"] = [f"TXN{i:08d}" for i in range(len(df))]
    df = df[[
        "transaction_id", "customer_id", "timestamp", "amount_clp",
        "merchant_category", "latitude", "longitude", "is_fraud",
    ]]
    return df


if __name__ == "__main__":
    import pathlib

    out_dir = pathlib.Path(__file__).resolve().parents[2] / "data" / "raw"
    out_dir.mkdir(parents=True, exist_ok=True)

    df = generate_dataset()
    out_path = out_dir / "transactions.parquet"
    df.to_parquet(out_path, index=False)

    fraud_pct = 100 * df["is_fraud"].mean()
    print(f"Generated {len(df):,} transactions -> {out_path}")
    print(f"Fraud rate: {fraud_pct:.3f}%  ({df['is_fraud'].sum():,} fraudulent rows)")
    print(f"Customers: {df['customer_id'].nunique():,}")
    print(f"Date range: {df['timestamp'].min()} -> {df['timestamp'].max()}")
